### ISSUE TITLE
Move calibration interpolation into controller

### ISSUE THREAD

**Issue by raimund-schluessler** [BrillouinMicroscopy/bmlab#22]
The interpolation for the calibration only needs to be done once, when the underlying data changes. Not on every function call.

https://github.com/BrillouinMicroscopy/bmlab/blob/main/bmlab/models/calibration_model.py#L183-L197
https://github.com/BrillouinMicroscopy/bmlab/blob/main/bmlab/models/calibration_model.py#L151-L161

**Comment by matthias-baer** [comment]
I have started restructuring session / controllers / models. First, I moved some logic from the session to the controllers.

Then I noticed that so far we had one module per controller class. This is very inconvenient because this easily causes circular imports. That's why I have put all controllers in one module, which is common practice in Python. If necessary, we can split it up into different modules later when we have made sure that the controllers do not depend directly on each other.

**Comment by raimund-schluessler** [comment]
I would propose to structure it in a way that every function which modifies data in a model (and might need access to multiple models), is located in the controller. And every function which only reads data from a single model and does not modify the model goes into the model.

**Comment by raimund-schluessler** [comment]
> 
> 
> I would propose to structure it in a way that every function which modifies data in a model (and might need access to multiple models), is located in the controller. And every function which only reads data from a single model and does not modify the model goes into the model.

This should also prevent having to use e.g. the ExtractionController from the CalibrationController.
